select * from glasses;
select * from student;
select * from glasses;
create Table test1 as select * from glasses;
create Table test2 as select * from glasses;
select * from test1;
desc test1;
select * from student;
create table test3 as select name, price, review from glasses;
select * from test3;
select * from glasses;
create table test4 as select * from glasses where price >= 700000;
select * from glasses;
select * from test4;
create table test5 as select name, price, review from glasses where price < 500000;
select * from test5;
drop table test;
create table test6 as select * from glasses where 1=2;
select * from test6;
insert into test6(name, price, optColor) select name, price, optColor from glasses;
select * from test6;
select * from glasses;
select * from test6;
insert into test6(name, price, optColor, orderNumber) select name, price, optColor, orderNumber from glasses;
desc glasses;
select * from test6;
insert into test5(name,price,optColor,orderNumber,review) select name,price,optColor,orderNumber,review from test6;
select * from test5;
rename table test6 to newTest6;
select * from newtest6;
truncate newtest6;
select * from newtest6;
desc newtest6;
drop table newtest6;
desc newtest6;
select * from newtest6;